### ISSUE TITLE
opencollada tools in wiki downloads not working

### ISSUE THREAD

**Issue by seredahmet** [KhronosGroup/OpenCOLLADA#324]
the links gives : forbidden error, what is the problem

**Comment by RemiArnaud** [comment]
Thanks to reporting the issue.

archives are down. 
Not a major issue because up to date exporters are available with the 'Latest binaries' link provided in the wiki page.
can you follow that link and get the exporter you need?

assigning to Khronos Web master to see why downloads don't work on collada.org

**Comment by Khronoswebmaster** [comment]
You can now download the files from collada.org.

**Comment by RemiArnaud** [comment]
thank you!
