### ISSUE TITLE
Maya 2016 x64 Windows 7: Build #59: Crash when importing single triangle

### ISSUE THREAD

**Issue by jamgram** [KhronosGroup/OpenCOLLADA#337]
When I export a mesh that is a single triangle to a collada file and try to import that collada file into a new scene, maya crashes. I had a collada file with several meshes and one of them was a single triangle mesh and was crashing on that mesh. When that single triangle mesh was removed from the collada file it imported fine. I am using the latest release build from github, #59.

**Comment by RemiArnaud** [comment]
could you be so kind to provide a collada document that crashes the importer?
Thanks

**Comment by jamgram** [comment]
Hi Remi,
Absolutely, how should I get it to you? I created the file by creating a new scene, making a quad, deleting one triangle and exporting with the opencollada exporter.

**Comment by RemiArnaud** [comment]
Thanks to @jamgram help, I compared the .ma created by openCollada and the one created by Maya directly.
I was able to find the one difference that crashes Maya on import.
inside the ```createNode mesh``` the ```setAttr ".fc[0:0]" -type "polyFaces"``` line exported by openCollada need to be changed to ```setAttr ".fc[0]" -type "polyFaces"```, and the issue is fixed.

@jamgram - could you confirm this work around works for your files? you'd have to hand modify the .ma files created by the exporter and manually import them.

@mycheckgithub - I have not looked at the importer code, could you take a look? it should be an easy fix?

**Comment by jamgram** [comment]
@RemiArnaud Yes, that change in the .ma file worked. Maya does not crash when opening it now.

**Comment by mycheckgithub** [comment]
There was a fix for single face geometries, but only builded for maya 2013 version.
Now it is applied for all maya version > 2013

**Comment by RemiArnaud** [comment]
thanks for the fix
now merged, so closing this issue.
